### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by Mungbeanz** [Willmac16/OctoPrint-GcodeLeveling#10]
Hi,

Seem to be getting upload failed every time I try to upload a .gcode file.
With the option enable to upload a non-modified file, I get the error and a non-modified file uploaded.
Without that option enabled I just get the error.
Disabling plugin I get no error.
![upload error](https://user-images.githubusercontent.com/33512163/105619729-6f29a580-5e5a-11eb-8bec-eef317da78cc.PNG)

**Comment by Willmac16** [comment]
@Mungbeanz Could you upload your octoprint.log file from the Logging tab in settings.

**Comment by Mungbeanz** [comment]
[octoprint.log](https://github.com/Willmac16/OctoPrint-GcodeLeveling/files/5861512/octoprint.log)
Log uploaded

**Comment by Willmac16** [comment]
@Mungbeanz can you upload a screenshot of your GcodeLeveling setting and the gcode file this failed on.

**Comment by Mungbeanz** [comment]
![Level settings](https://user-images.githubusercontent.com/33512163/105620444-1eb64600-5e62-11eb-9bd7-ea7f4b383e4b.PNG)
Attached level settings

**Comment by Mungbeanz** [comment]
Had to upload PDf of file.  cant directly link gcode file here without wall of text

[Gcode.pdf](https://github.com/Willmac16/OctoPrint-GcodeLeveling/files/5861535/Gcode.pdf)

**Comment by Willmac16** [comment]
@Mungbeanz after some digging I finally found the culprit (this is some added logging in a work in progress version).

`octoprint.plugins.gcodeleveling - INFO - Failed Leveling Point: 80.0, 0.0, -0.06992557150451786`

It appears that one of the generated endpoints is slightly below 0. If your machine can can move to that position, then you should lower the minimum z value; otherwise, you should bring the points up a little bit since the model believes that the bed goes below 0.

**Comment by Mungbeanz** [comment]
Wow,  that was some good troubleshooting and a half.  thanks for you help.
How did you find the XYZ values?

**Comment by Willmac16** [comment]
I added in that printout into the logger (in some unreleased code) when it errors since I was debugging an issue with my test setup. If you wanted to have that and some other prerelease code You can install it in the plugin manager with the url https://github.com/willmac16/OctoPrint-GcodeLeveling/archive/devel.zip.

**Comment by gonzagarra** [comment]
I am getting the same error with the "aro2.gcode" file. I tried to lower the minimum value of Z to -5 but it didn't work. Anyway I tried another "nut14.gcode" file and it worked. I think there is a problem with the gcode processing. I uploaded captures, files and log.
[files.zip](https://github.com/Willmac16/OctoPrint-GcodeLeveling/files/5868017/files.zip)

**Comment by Willmac16** [comment]
@gonzagarra thank you for the files. I tried your gcode files on my test setup and have some recommendations

+ Could you first decrease the polynomial degree settings as shown in the screenshot.
<img width="528" alt="image" src="https://user-images.githubusercontent.com/27445690/105742069-e6f5df80-5eef-11eb-81c8-00d4865e2afe.png">

+ Then test with your files and see if it works


+ If that fails, please try to enter the points like
<img width="650" alt="image" src="https://user-images.githubusercontent.com/27445690/105741462-2d970a00-5eef-11eb-9092-d60d5e66a2b4.png">

+ report back what worked

**Comment by Mungbeanz** [comment]
My problem is resolved.
I had some other issues with the start and end gcode getting corrupted by the addon. (doing odd movements and mega retractions).  This start and end script was added by the slicer.
I moved this over to Octopi to do the start and end scripts and since this doesn't go into the edited file by the addon it no longer causes an issue.

**Comment by gonzagarra** [comment]
@Willmac16 Apparently it worked by changing the polynomial value, but again it went back to the previous value and kept working. I'm going to do some tests and then I report. Thank you.
