### ISSUE TITLE
Formatted Gcode missing E pos

### ISSUE THREAD

**Issue by themalse** [Willmac16/OctoPrint-GcodeLeveling#4]
I uploaded a file to test but the resulting Gcode no longer has E values. It will draw but not extrude any filament.

**Comment by Willmac16** [comment]
I added in E pos handling to the devel branch, but I was wondering what your use case for the plugin is. I made this plugin because I am building a grbl cnc machine and I don't have a way to level in the firmware. I wasn't sure if there was any use for this plugin beyond certain cnc setups, so I didn't attempt to implement E support at first.

If you do want to install the devel branch you can with this url in the plugin manager https://github.com/willmac16/OctoPrint-GcodeLeveling/archive/devel.zip

Best,
Will
